<?php
require_once __DIR__ . '/../Config/auth.php'; requireLogin();
$activeMenu='router'; $routerView='client_history';
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Client History - NetMonitor</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link rel="stylesheet" href="../assets/css/variables.css"><link rel="stylesheet" href="../assets/css/common.css"><link rel="stylesheet" href="../assets/css/theme.css?v=1"><link rel="stylesheet" href="../assets/css/router_subnav.css?v=2"><link rel="stylesheet" href="../assets/css/global_responsive.css?v=1"><link rel="stylesheet" href="../assets/css/router_client_history.css?v=1"></head><body><?php include __DIR__.'/../includes/sidebar.php'; ?>
<main class="main-content client-history-page"><div class="page-header"><div><h1 class="page-title">Client Traffic History</h1><div class="page-subtitle">Riwayat penggunaan bandwidth per client / IP.</div></div><span id="historyStatus" class="client-live"><i class="bi bi-clock-history"></i> Memuat data...</span></div>
<section class="history-toolbar card-modern"><div><label>Router</label><select id="historyRouter" class="form-select form-select-sm"></select></div><div><label>Client / IP</label><select id="historyClient" class="form-select form-select-sm"><option value="">Pilih client...</option></select></div><div><label>Periode</label><select id="historyRange" class="form-select form-select-sm"><option value="24h">24 Jam</option><option value="7d">7 Hari</option><option value="30d">30 Hari</option></select></div></section>
<section class="history-stats"><div class="stat-card"><div class="stat-title">Rata-rata Download</div><div class="stat-value" id="avgDown">0.00 Mbps</div></div><div class="stat-card"><div class="stat-title">Rata-rata Upload</div><div class="stat-value" id="avgUp">0.00 Mbps</div></div><div class="stat-card"><div class="stat-title">Peak Download</div><div class="stat-value" id="peakDown">0.00 Mbps</div></div><div class="stat-card"><div class="stat-title">Peak Upload</div><div class="stat-value" id="peakUp">0.00 Mbps</div></div><div class="stat-card"><div class="stat-title">Total Sample</div><div class="stat-value" id="sampleCount">0</div></div></section>
<section class="history-grid"><div class="card-modern history-chart-card"><div class="card-heading"><div><h2>Traffic Trend</h2><p id="clientTitle">Pilih client untuk melihat histori.</p></div><span id="historyCount">0 sample</span></div><div class="chart-wrap"><canvas id="clientHistoryChart"></canvas></div></div><div class="card-modern peak-card"><div class="card-heading"><div><h2>Peak Usage</h2><p>Waktu penggunaan tertinggi.</p></div></div><div class="peak-row"><span>Peak Download</span><strong id="peakDownAt">-</strong></div><div class="peak-row"><span>Peak Upload</span><strong id="peakUpAt">-</strong></div><div class="client-summary" id="clientSummary">Belum ada histori client.</div></div></section>
<section class="card-modern history-table-card"><div class="card-heading"><div><h2>Data Histori</h2><p>Snapshot client yang tersimpan secara berkala.</p></div></div><div class="table-responsive"><table class="table table-modern"><thead><tr><th>Waktu</th><th>Client / IP</th><th>Sumber</th><th>Download</th><th>Upload</th><th>Total</th></tr></thead><tbody id="historyBody"><tr><td colspan="6" class="text-center py-4 text-muted">Pilih client.</td></tr></tbody></table></div></section>
</main><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script src="../assets/js/router_client_history.js?v=1"></script></body></html>
