<?php
require_once __DIR__ . '/../Config/auth.php'; requireLogin();
$activeMenu='router'; $routerView='client_usage_analytics';
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Client Usage Analytics - NetMonitor</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link rel="stylesheet" href="../assets/css/variables.css"><link rel="stylesheet" href="../assets/css/common.css"><link rel="stylesheet" href="../assets/css/theme.css?v=1"><link rel="stylesheet" href="../assets/css/router_subnav.css?v=3"><link rel="stylesheet" href="../assets/css/global_responsive.css?v=1"><link rel="stylesheet" href="../assets/css/router_client_usage_analytics.css?v=1"></head><body><?php include __DIR__.'/../includes/sidebar.php'; ?>
<main class="main-content client-usage-page"><div class="page-header"><div><h1 class="page-title">Client Usage Analytics</h1><div class="page-subtitle">Ranking pemakaian bandwidth berdasarkan histori client.</div></div><span id="usageStatus" class="client-live"><i class="bi bi-bar-chart"></i> Memuat data...</span></div>
<section class="usage-toolbar card-modern"><div><label>Router</label><select id="usageRouter" class="form-select form-select-sm"></select></div><div><label>Periode</label><select id="usageRange" class="form-select form-select-sm"><option value="24h">24 Jam</option><option value="7d" selected>7 Hari</option><option value="30d">30 Hari</option></select></div><div><label>Jumlah Ranking</label><select id="usageLimit" class="form-select form-select-sm"><option value="10" selected>Top 10</option><option value="25">Top 25</option><option value="50">Top 50</option></select></div></section>
<section class="usage-stats"><div class="stat-card"><div class="stat-title">Total Client</div><div class="stat-value" id="totalClients">0</div></div><div class="stat-card"><div class="stat-title">Top Client</div><div class="stat-value compact" id="topClient">-</div></div><div class="stat-card"><div class="stat-title">Peak Download</div><div class="stat-value" id="topPeakDown">0.00 Mbps</div></div><div class="stat-card"><div class="stat-title">Peak Upload</div><div class="stat-value" id="topPeakUp">0.00 Mbps</div></div><div class="stat-card"><div class="stat-title">Total Data Top Client</div><div class="stat-value" id="topData">0.00 GB</div></div></section>
<section class="usage-grid"><div class="card-modern ranking-card"><div class="card-heading"><div><h2>Client Usage Ranking</h2><p>Diurutkan berdasarkan rata-rata download + upload.</p></div><span id="rankingCount">0 client</span></div><div class="table-responsive"><table class="table table-modern"><thead><tr><th>#</th><th>Client / IP</th><th>Avg Down</th><th>Avg Up</th><th>Peak Down</th><th>Peak Up</th><th>Estimasi Data</th><th>Sample</th></tr></thead><tbody id="rankingBody"><tr><td colspan="8" class="text-center py-4 text-muted">Memuat...</td></tr></tbody></table></div></div><div class="card-modern top-card"><div class="card-heading"><div><h2>Top Client</h2><p>Client paling dominan pada periode terpilih.</p></div></div><div id="topBox" class="top-box"><div class="top-rank">#1</div><div class="top-name" id="topName">-</div><div class="top-ip" id="topIp">-</div><div class="top-metrics"><span>Avg <strong id="topAvg">0.00 Mbps</strong></span><span>Peak <strong id="topPeak">0.00 Mbps</strong></span></div><div class="top-progress"><span id="topProgress"></span></div></div></div></section>
<section class="card-modern insight-card"><div class="card-heading"><div><h2>Insight Pemakaian</h2><p>Ringkasan otomatis berdasarkan histori yang tersedia.</p></div></div><div id="usageInsight" class="usage-insight">Belum ada data histori client.</div></section>
</main><script src="../assets/js/router_client_usage_analytics.js?v=2"></script></body></html>
