<?php
require_once __DIR__ . '/../Config/auth.php';
requireLogin();
$activeMenu='router';$routerView='traffic_clients';
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Client Analytics - NetMonitor</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link rel="stylesheet" href="../assets/css/variables.css"><link rel="stylesheet" href="../assets/css/common.css"><link rel="stylesheet" href="../assets/css/theme.css?v=1"><link rel="stylesheet" href="../assets/css/router_subnav.css?v=2"><link rel="stylesheet" href="../assets/css/global_responsive.css?v=1"><link rel="stylesheet" href="../assets/css/router_traffic_clients.css?v=2"></head><body>
<?php include __DIR__.'/../includes/sidebar.php'; ?>
<main class="main-content client-page"><div class="page-header"><div><h1 class="page-title">Client / IP Analytics</h1><div class="page-subtitle">Analisis traffic client berdasarkan IP, Simple Queue, HotSpot, dan PPPoE.</div></div><span id="clientStatus" class="client-live"><i class="bi bi-broadcast"></i> Memuat data...</span></div>
<section class="client-toolbar card-modern"><div><label>Router</label><select id="clientRouter" class="form-select form-select-sm"></select></div><div><label>Pencarian</label><input id="clientSearch" class="form-control form-control-sm" placeholder="Cari IP atau nama client..."></div><div><label>Urutkan</label><select id="clientSort" class="form-select form-select-sm"><option value="traffic">Traffic</option><option value="download">Download</option><option value="upload">Upload</option><option value="connections">Connections</option><option value="ip">IP</option></select></div></section>
<section class="client-stats"><div class="stat-card"><div class="stat-title">Total Client</div><div class="stat-value" id="totalClients">0</div></div><div class="stat-card"><div class="stat-title">Download Saat Ini</div><div class="stat-value" id="totalDownload">0.00 Mbps</div></div><div class="stat-card"><div class="stat-title">Upload Saat Ini</div><div class="stat-value" id="totalUpload">0.00 Mbps</div></div><div class="stat-card"><div class="stat-title">Top Client</div><div class="stat-value" id="topClient">-</div></div></section>
<section class="client-grid"><div class="card-modern client-table-card"><div class="card-heading"><div><h2>Ranking Client / IP</h2><p>Diurutkan berdasarkan traffic saat ini.</p></div><span id="clientCountLabel">0 client</span></div><div class="table-responsive"><table class="table table-modern"><thead><tr><th>#</th><th>Client / IP</th><th>Sumber</th><th>Download</th><th>Upload</th><th>Total</th><th>Connections</th></tr></thead><tbody id="clientBody"><tr><td colspan="7" class="text-center py-4 text-muted">Memuat data...</td></tr></tbody></table></div></div><div class="card-modern top-client-card"><div class="card-heading"><div><h2>Top Client</h2><p>Client dengan traffic tertinggi.</p></div></div><div id="topClientBox" class="top-client-empty">Belum ada data client.</div></div></section>
<section class="card-modern client-note"><i class="bi bi-clock-history"></i><div><strong>Riwayat Client</strong><p>Snapshot client sekarang disimpan berkala oleh collector. Buka <a href="client_history.php">Client Traffic History</a> untuk melihat grafik dan statistik per-IP.</p></div></section></main>
<script src="../assets/js/router_traffic_clients.js?v=2"></script></body></html>
