<?php
require_once __DIR__ . '/../config/database.php';
$id=(int)($_GET['id']??0);
if($id<=0){http_response_code(400);exit('ID tidak valid.');}
try{$pdo=(new Database())->connect();$st=$pdo->prepare("SELECT i.*,c.name,c.phone,c.address,c.pppoe_username,c.package_name FROM billing_invoices i JOIN billing_customers c ON c.id=i.customer_id WHERE i.id=? AND i.status='paid'");$st->execute([$id]);$r=$st->fetch(PDO::FETCH_ASSOC);if(!$r){http_response_code(404);exit('Pembayaran tidak ditemukan.');}}catch(Throwable $e){http_response_code(500);exit('Gagal mengambil data.');}
function h($v){return htmlspecialchars((string)($v??'-'),ENT_QUOTES,'UTF-8');}
function rupiah($v){return 'Rp '.number_format((float)$v,0,',','.');}
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kwitansi <?=h($r['invoice_no'])?></title>
<style>body{font-family:Arial;margin:0;background:#eef2f7;color:#10203a}.receipt{width:min(700px,calc(100% - 30px));margin:35px auto;background:#fff;padding:35px;border:1px solid #d9e1ec;box-shadow:0 8px 30px #0001}.top{display:flex;justify-content:space-between;border-bottom:2px solid #10203a;padding-bottom:18px}.brand{font-size:25px;font-weight:700}.title{text-align:right;font-size:24px;font-weight:700}.muted{color:#65758f;font-size:13px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:25px 0}.label{font-size:12px;color:#65758f;margin-bottom:5px}.value{font-weight:600}.amount{font-size:25px;font-weight:700;margin:25px 0;padding:18px;background:#f3f7fc;border-radius:8px}.status{display:inline-block;padding:6px 10px;border-radius:99px;background:#d9f1e6;color:#08774e;font-weight:700;font-size:12px}.foot{border-top:1px solid #ddd;margin-top:30px;padding-top:18px;font-size:12px;color:#65758f}.actions{text-align:center;margin:20px}.btn{padding:10px 16px;border:0;border-radius:6px;background:#087cff;color:#fff;font-weight:700;cursor:pointer}@media print{body{background:#fff}.receipt{width:auto;margin:0;box-shadow:none;border:0}.actions{display:none}}</style></head><body>
<div class="receipt"><div class="top"><div><div class="brand">NetMonitor</div><div class="muted">Billing PPPoE</div></div><div class="title">KWITANSI<br><span class="muted"><?=h($r['invoice_no'])?></span></div></div>
<div class="grid"><div><div class="label">Diterima dari</div><div class="value"><?=h($r['name'])?></div><div class="muted"><?=h($r['phone'])?></div></div><div><div class="label">Username PPPoE</div><div class="value"><?=h($r['pppoe_username'])?></div><div class="muted">Paket <?=h($r['package_name'])?></div></div><div><div class="label">Periode</div><div class="value"><?=h($r['period'])?></div></div><div><div class="label">Tanggal pembayaran</div><div class="value"><?=h($r['paid_at'])?></div></div></div>
<div class="amount"><?=rupiah($r['amount'])?> <span class="status">LUNAS</span></div>
<div class="grid"><div><div class="label">Metode pembayaran</div><div class="value"><?=h($r['payment_method']?:'Cash')?></div></div><div><div class="label">Catatan</div><div class="value"><?=h($r['notes']?:'-')?></div></div></div>
<div class="foot">Terima kasih atas pembayaran pelanggan NetMonitor.<br>Kwitansi ini dibuat oleh sistem Billing PPPoE.</div></div><div class="actions"><button class="btn" onclick="window.print()">Cetak Kwitansi</button></div></body></html>