<?php
require_once __DIR__ . '/../Config/database.php';
header('Content-Type: application/json; charset=utf-8');date_default_timezone_set('Asia/Jakarta');
function cj($ok,$message='',$data=[],$code=200){http_response_code($code);echo json_encode(array_merge(['success'=>$ok,'message'=>$message],$data),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
try{$pdo=(new Database())->connect();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$a=strtolower($_GET['action']??'list');
if($a==='list'){$q=trim($_GET['q']??'');$status=$_GET['status']??'all';$w=[];$v=[];if($q!==''){$w[]='(c.name LIKE ? OR c.pppoe_username LIKE ? OR c.phone LIKE ? OR c.package_name LIKE ?)';$x="%$q%";array_push($v,$x,$x,$x,$x);}if(in_array($status,['active','suspended'],true)){$w[]='c.status=?';$v[]=$status;}$sql="SELECT c.id,c.name,c.phone,c.address,c.pppoe_username,c.package_name,c.monthly_price,c.billing_day,c.status,c.notes,c.created_at,c.updated_at,COALESCE(u.unpaid_count,0) unpaid_count,COALESCE(u.unpaid_amount,0) unpaid_amount FROM billing_customers c LEFT JOIN (SELECT customer_id,COUNT(*) unpaid_count,SUM(amount) unpaid_amount FROM billing_invoices WHERE status='unpaid' GROUP BY customer_id) u ON u.customer_id=c.id".($w?' WHERE '.implode(' AND ',$w):'')." ORDER BY c.name ASC LIMIT 1000";$s=$pdo->prepare($sql);$s->execute($v);$rows=$s->fetchAll(PDO::FETCH_ASSOC);$r=$pdo->query("SELECT COUNT(*) total,SUM(status='active') active,SUM(status='suspended') suspended FROM billing_customers")->fetch(PDO::FETCH_ASSOC)?:[];cj(true,'',['customers'=>$rows,'summary'=>['total'=>(int)$r['total'],'active'=>(int)$r['active'],'suspended'=>(int)$r['suspended']]]);}
if($a==='save'){$id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');$phone=trim($_POST['phone']??'');$address=trim($_POST['address']??'');$pppoe=trim($_POST['pppoe_username']??'');$package=trim($_POST['package_name']??'');$price=max(0,(float)($_POST['monthly_price']??0));$day=max(1,min(31,(int)($_POST['billing_day']??1)));$status=in_array($_POST['status']??'active',['active','suspended'],true)?$_POST['status']:'active';$notes=trim($_POST['notes']??'');if($name===''||$pppoe===''||$package==='')cj(false,'Nama, username PPPoE, dan paket wajib diisi.',[],422);if($id){$s=$pdo->prepare('UPDATE billing_customers SET name=?,phone=?,address=?,pppoe_username=?,package_name=?,monthly_price=?,billing_day=?,status=?,notes=? WHERE id=?');$s->execute([$name,$phone,$address,$pppoe,$package,$price,$day,$status,$notes,$id]);cj(true,'Pelanggan berhasil diperbarui.',['id'=>$id]);}else{$s=$pdo->prepare('INSERT INTO billing_customers(name,phone,address,pppoe_username,package_name,monthly_price,billing_day,status,notes) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute([$name,$phone,$address,$pppoe,$package,$price,$day,$status,$notes]);cj(true,'Pelanggan berhasil ditambahkan.',['id'=>(int)$pdo->lastInsertId()]);}}
if($a==='delete'){$id=(int)($_POST['id']??0);if($id<=0)cj(false,'ID pelanggan tidak valid.',[],422);$s=$pdo->prepare('DELETE FROM billing_customers WHERE id=?');try{$s->execute([$id]);cj($s->rowCount()>0,$s->rowCount()>0?'Pelanggan dihapus.':'Pelanggan tidak ditemukan.',[], $s->rowCount()>0?200:404);}catch(PDOException $e){cj(false,'Pelanggan tidak dapat dihapus karena masih memiliki invoice.',[],409);}}
if($a==='pppoe_accounts'){$r=@file_get_contents('http://127.0.0.1/NetworkMonitor/api/pppoe.php?action=secrets');if($r===false)$r=@file_get_contents('../api/pppoe.php?action=secrets');$j=json_decode($r?:'',true);$accounts=[];foreach(($j['secrets']??$j['data']??[]) as $x){$accounts[]=['name'=>$x['name']??$x['username']??'','profile'=>$x['profile']??'','service'=>$x['service']??'','disabled'=>($x['disabled']??false)===true];}cj(true,'',['accounts'=>$accounts]);}
cj(false,'Action tidak dikenal.',[],404);}catch(Throwable $e){cj(false,$e->getMessage(),[],500);}
