<?php
require_once __DIR__ . '/../Config/database.php';
header('Content-Type: application/json; charset=utf-8');date_default_timezone_set('Asia/Jakarta');
function j($ok,$message='',$data=[],$code=200){http_response_code($code);echo json_encode(array_merge(['success'=>$ok,'message'=>$message],$data),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
try{$pdo=(new Database())->connect();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$action=$_GET['action']??'list';
if($action==='list'){$month=$_GET['month']??date('Y-m');$status=$_GET['status']??'all';$q=trim($_GET['q']??'');$w=[];$a=[];if(preg_match('/^\d{4}-\d{2}$/',$month)){$w[]='i.period BETWEEN ? AND ?';$a[]=$month.'-01';$a[]=date('Y-m-t',strtotime($month.'-01'));}if(in_array($status,['unpaid','paid','cancelled'],true)){$w[]='i.status=?';$a[]=$status;}if($q!==''){$w[]='(i.invoice_no LIKE ? OR c.name LIKE ? OR c.pppoe_username LIKE ?)';$x="%$q%";array_push($a,$x,$x,$x);}$sql="SELECT i.*,c.name customer_name,c.pppoe_username,c.package_name FROM billing_invoices i JOIN billing_customers c ON c.id=i.customer_id".($w?' WHERE '.implode(' AND ',$w):'')." ORDER BY i.due_date ASC,i.id DESC LIMIT 500";$s=$pdo->prepare($sql);$s->execute($a);j(true,'',['invoices'=>$s->fetchAll(PDO::FETCH_ASSOC)]);}
if($action==='generate'){$month=trim($_POST['month']??date('Y-m'));if(!preg_match('/^\d{4}-\d{2}$/',$month))j(false,'Bulan tidak valid.',[],422);$period=$month.'-01';$dueDay=max(1,min(31,(int)($_POST['due_day']??1)));$customers=$pdo->query("SELECT id,name,monthly_price,billing_day FROM billing_customers WHERE status='active' ORDER BY id")->fetchAll(PDO::FETCH_ASSOC);$created=0;$skipped=0;$s=$pdo->prepare("INSERT INTO billing_invoices(customer_id,invoice_no,period,amount,due_date,status) VALUES(?,?,?,?,?,'unpaid')");foreach($customers as $c){$chk=$pdo->prepare('SELECT id FROM billing_invoices WHERE customer_id=? AND period=?');$chk->execute([$c['id'],$period]);if($chk->fetchColumn()){$skipped++;continue;}$day=$dueDay>1?$dueDay:(int)$c['billing_day'];$days=(int)date('t',strtotime($period));$day=min(max(1,$day),$days);$due=$month.'-'.str_pad($day,2,'0',STR_PAD_LEFT);$no='INV-'.$month.'-'.str_pad((int)$c['id'],5,'0',STR_PAD_LEFT);$s->execute([$c['id'],$no,$period,(float)$c['monthly_price'],$due]);$created++;}j(true,'Invoice berhasil digenerate.',['created'=>$created,'skipped'=>$skipped,'total'=>count($customers)]);}
if($action==='cancel'){$id=(int)($_POST['invoice_id']??0);$s=$pdo->prepare("UPDATE billing_invoices SET status='cancelled' WHERE id=? AND status='unpaid'");$s->execute([$id]);j($s->rowCount()>0,$s->rowCount()>0?'Invoice dibatalkan.':'Invoice tidak ditemukan atau sudah diproses.',[], $s->rowCount()>0?200:422);}
if($action==='restore'){$id=(int)($_POST['invoice_id']??0);$s=$pdo->prepare("UPDATE billing_invoices SET status='unpaid' WHERE id=? AND status='cancelled'");$s->execute([$id]);j($s->rowCount()>0,$s->rowCount()>0?'Invoice dikembalikan menjadi belum bayar.':'Invoice tidak dapat dipulihkan.',[], $s->rowCount()>0?200:422);}
j(false,'Action tidak dikenal.',[],404);}catch(Throwable $e){j(false,$e->getMessage(),[],500);}
