<?php
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
try{
 require_once __DIR__.'/../Config/database.php';
 $pdo=(new Database())->connect();
 try{$pdo->exec("SET time_zone = '+07:00'");}catch(Throwable $ignore){}
 $input=json_decode(file_get_contents('php://input'),true);if(!is_array($input))$input=$_POST;
 $routerId=(int)($input['router_id']??0);$routerName=trim((string)($input['router_name']??'Router'));$events=$input['events']??[];$connectEvents=$input['connect_events']??[];
 if($routerId<=0||(!is_array($events)&&!is_array($connectEvents))||(!$events&&!$connectEvents)){echo json_encode(['success'=>true,'sent'=>0,'skipped'=>0,'logged'=>0,'health_alerts'=>0,'reconnect_sent'=>0]);exit;}
 $pdo->exec("CREATE TABLE IF NOT EXISTS pppoe_disconnect_history (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,event_key CHAR(64) NULL,router_id INT NOT NULL,router_name VARCHAR(128) NULL,username VARCHAR(128) NOT NULL,address VARCHAR(64) NULL,profile VARCHAR(128) NULL,caller_id VARCHAR(128) NULL,uptime VARCHAR(64) NULL,uptime_seconds BIGINT NULL,disconnected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_disconnect_event(event_key),KEY idx_router_time(router_id,disconnected_at),KEY idx_user_time(username,disconnected_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 try{$cols=$pdo->query("SHOW COLUMNS FROM pppoe_disconnect_history LIKE 'event_key'")->fetchAll();if(!$cols){$pdo->exec("ALTER TABLE pppoe_disconnect_history ADD COLUMN event_key CHAR(64) NULL AFTER id");$pdo->exec("ALTER TABLE pppoe_disconnect_history ADD UNIQUE KEY uq_disconnect_event(event_key)");}}catch(Throwable $ignore){}
 try{$cols=$pdo->query("SHOW COLUMNS FROM pppoe_disconnect_history LIKE 'uptime_seconds'")->fetchAll();if(!$cols)$pdo->exec("ALTER TABLE pppoe_disconnect_history ADD COLUMN uptime_seconds BIGINT NULL AFTER uptime");}catch(Throwable $ignore){}
 $q=$pdo->query("SELECT setting_name,setting_value FROM settings WHERE setting_name IN ('telegram_enabled','telegram_bot_token','telegram_chat_id')");$cfg=$q->fetchAll(PDO::FETCH_KEY_PAIR);$enabled=($cfg['telegram_enabled']??'0')==='1';$token=trim((string)($cfg['telegram_bot_token']??''));$chat=trim((string)($cfg['telegram_chat_id']??''));
 $pdo->exec("CREATE TABLE IF NOT EXISTS telegram_pppoe_disconnect_log (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,event_key CHAR(64) NOT NULL,router_id INT NOT NULL,username VARCHAR(128) NOT NULL,session_id VARCHAR(128) NULL,notified_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_event(event_key),KEY idx_router_user(router_id,username,notified_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS telegram_pppoe_reconnect_log (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,reconnect_key CHAR(64) NOT NULL,router_id INT NOT NULL,username VARCHAR(128) NOT NULL,session_id VARCHAR(128) NULL,notified_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_reconnect(reconnect_key),KEY idx_router_user(router_id,username,notified_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS pppoe_health_alert_state (router_id INT NOT NULL,username VARCHAR(128) NOT NULL,current_level VARCHAR(16) NOT NULL DEFAULT 'normal',current_score INT NOT NULL DEFAULT 100,last_notified_level VARCHAR(16) NULL,last_notified_at DATETIME NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(router_id,username),KEY idx_health_level(router_id,current_level)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $reserve=$pdo->prepare('INSERT IGNORE INTO telegram_pppoe_disconnect_log(event_key,router_id,username,session_id) VALUES(?,?,?,?)');$remove=$pdo->prepare('DELETE FROM telegram_pppoe_disconnect_log WHERE event_key=?');
 $reconnectReserve=$pdo->prepare('INSERT IGNORE INTO telegram_pppoe_reconnect_log(reconnect_key,router_id,username,session_id) VALUES(?,?,?,?)');$reconnectRemove=$pdo->prepare('DELETE FROM telegram_pppoe_reconnect_log WHERE reconnect_key=?');
 $history=$pdo->prepare('INSERT IGNORE INTO pppoe_disconnect_history(event_key,router_id,router_name,username,address,profile,caller_id,uptime,uptime_seconds,disconnected_at) VALUES(?,?,?,?,?,?,?,?,?,NOW())');
 $stateGet=$pdo->prepare('SELECT current_level,current_score,last_notified_level,last_notified_at FROM pppoe_health_alert_state WHERE router_id=? AND username=? LIMIT 1');
 $stateSave=$pdo->prepare("INSERT INTO pppoe_health_alert_state(router_id,username,current_level,current_score,last_notified_level,last_notified_at) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE current_level=VALUES(current_level),current_score=VALUES(current_score),last_notified_level=COALESCE(VALUES(last_notified_level),last_notified_level),last_notified_at=COALESCE(VALUES(last_notified_at),last_notified_at),updated_at=CURRENT_TIMESTAMP");
 $parseUptime=function($s){$s=trim((string)$s);if($s===''||$s==='-')return null;$total=0;$matched=false;$rx=['w'=>604800,'d'=>86400,'h'=>3600,'m'=>60,'s'=>1];foreach($rx as $u=>$mul){if(preg_match('/(\\d+)'.preg_quote($u,'/').'/i',$s,$m)){$total+=(int)$m[1]*$mul;$matched=true;}}return $matched?$total:null;};
 $fmtUptime=function($seconds){if($seconds===null)return '-';$seconds=max(0,(int)$seconds);$d=intdiv($seconds,86400);$seconds%=86400;$h=intdiv($seconds,3600);$seconds%=3600;$m=intdiv($seconds,60);$s=$seconds%60;$out=[];if($d)$out[]=$d.'d';if($h)$out[]=$h.'h';if($m)$out[]=$m.'m';if(!$out||$s)$out[]=$s.'s';return implode(' ',$out);};
 $levelRank=['normal'=>0,'attention'=>1,'warning'=>2,'critical'=>3];
 $sendTelegram=function($text)use($enabled,$token,$chat){if(!$enabled||$token===''||$chat==='')return [false,'not_configured'];$payload=json_encode(['chat_id'=>$chat,'text'=>$text,'parse_mode'=>'HTML','disable_web_page_preview'=>true]);$ch=curl_init('https://api.telegram.org/bot'.rawurlencode($token).'/sendMessage');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$payload,CURLOPT_HTTPHEADER=>['Content-Type: application/json'],CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>12]);$body=curl_exec($ch);$err=curl_error($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$res=is_string($body)?json_decode($body,true):null;return [$body!==false&&$code>=200&&$code<300&&!empty($res['ok']),$err!==''?$err:'Telegram menolak pesan'];};
 $sent=0;$skipped=0;$logged=0;$healthAlerts=0;$reconnectSent=0;$errors=[];
 foreach(array_slice(is_array($events)?$events:[],0,50) as $e){
  if(!is_array($e))continue;$username=trim((string)($e['name']??''));if($username==='')continue;$session=trim((string)($e['session_id']??''));$address=trim((string)($e['address']??'-'));$profile=trim((string)($e['profile']??'-'));$caller=trim((string)($e['caller_id']??'-'));$uptime=trim((string)($e['uptime']??'-'));$uptimeSeconds=$parseUptime($uptime);
  $eventKey=hash('sha256',$routerId.'|'.$username.'|'.$session.'|'.$address.'|'.$caller.'|'.$uptime);$history->execute([$eventKey,$routerId,$routerName,$username,$address,$profile,$caller,$uptime,$uptimeSeconds]);$isNewDisconnect=$history->rowCount()>0;if(!$isNewDisconnect){$skipped++;continue;}$logged++;
  $hq=$pdo->prepare("SELECT COUNT(*) disconnects,AVG(NULLIF(uptime_seconds,0)) avg_uptime_seconds FROM pppoe_disconnect_history WHERE router_id=? AND username=? AND disconnected_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)");$hq->execute([$routerId,$username]);$hr=$hq->fetch(PDO::FETCH_ASSOC)?:[];$d=(int)($hr['disconnects']??0);$avg=$hr['avg_uptime_seconds']!==null?(int)round((float)$hr['avg_uptime_seconds']):null;$score=100-min(70,$d*7);$reasons=[];if($d>=10)$reasons[]='Sering disconnect';elseif($d>=5)$reasons[]='Disconnect berulang';if($avg!==null&&$avg<3600){$score-=20;$reasons[]='Uptime pendek';}elseif($avg!==null&&$avg<7200){$score-=10;$reasons[]='Uptime relatif pendek';}$score=max(0,$score);if($score<40||$d>=10)$level='critical';elseif($score<70||$d>=5)$level='warning';elseif($d>=2)$level='attention';else $level='normal';if(!$reasons)$reasons[]='Pola koneksi normal';
  $stateGet->execute([$routerId,$username]);$old=$stateGet->fetch(PDO::FETCH_ASSOC)?:null;$lastNotified=$old&&$old['last_notified_level']!==null?(string)$old['last_notified_level']:null;$shouldHealthAlert=$levelRank[$level]>=2&&(!$lastNotified||$levelRank[$level]>($levelRank[$lastNotified]??0));$notifiedLevel=$lastNotified;$notifiedAt=$old['last_notified_at']??null;
  if($shouldHealthAlert){$reasonText=implode(', ',$reasons);$avgText=$fmtUptime($avg);$emoji=$level==='critical'?'🔴':'⚠️';$text=$emoji." <b>PPPoE USER HEALTH</b>\n\nRouter : <b>".htmlspecialchars($routerName,ENT_QUOTES,'UTF-8')."</b>\nUsername : <b>".htmlspecialchars($username,ENT_QUOTES,'UTF-8')."</b>\nStatus : <b>".strtoupper($level)."</b>\nStability Score : <b>".$score."/100</b>\nDisconnect 30 hari : <b>".$d."x</b>\nAvg uptime : <b>".htmlspecialchars($avgText,ENT_QUOTES,'UTF-8')."</b>\nAlasan : ".htmlspecialchars($reasonText,ENT_QUOTES,'UTF-8')."\nWaktu : ".date('d-m-Y H:i:s');[$ok,$err]=$sendTelegram($text);if($ok){$healthAlerts++;$notifiedLevel=$level;$notifiedAt=date('Y-m-d H:i:s');}elseif($err!=='not_configured')$errors[]=$username.' health: '.$err;}
  $stateSave->execute([$routerId,$username,$level,$score,$notifiedLevel,$notifiedAt]);
  if(!$enabled||$token===''||$chat==='')continue;$reserve->execute([$eventKey,$routerId,$username,$session!==''&&$session!=='-'?$session:null]);if($reserve->rowCount()===0)continue;
  $text="🔴 <b>PPPoE DISCONNECT</b>\n\nRouter : <b>".htmlspecialchars($routerName,ENT_QUOTES,'UTF-8')."</b>\nUsername : <b>".htmlspecialchars($username,ENT_QUOTES,'UTF-8')."</b>\nIP : ".htmlspecialchars($address,ENT_QUOTES,'UTF-8')."\nProfile : ".htmlspecialchars($profile,ENT_QUOTES,'UTF-8')."\nCaller-ID : ".htmlspecialchars($caller,ENT_QUOTES,'UTF-8')."\nUptime terakhir : ".htmlspecialchars($uptime,ENT_QUOTES,'UTF-8')."\nWaktu : ".date('d-m-Y H:i:s');[$ok,$err]=$sendTelegram($text);if(!$ok){$remove->execute([$eventKey]);if($err!=='not_configured')$errors[]=$username.': '.$err;continue;}$sent++;
 }
 foreach(array_slice(is_array($connectEvents)?$connectEvents:[],0,50) as $e){
  if(!is_array($e))continue;$username=trim((string)($e['name']??''));if($username==='')continue;$session=trim((string)($e['session_id']??''));$address=trim((string)($e['address']??'-'));$profile=trim((string)($e['profile']??'-'));$caller=trim((string)($e['caller_id']??'-'));$reconnectKey=hash('sha256',$routerId.'|'.$username.'|'.$session);
  if(!$enabled||$token===''||$chat==='')continue;$reconnectReserve->execute([$reconnectKey,$routerId,$username,$session!==''&&$session!=='-'?$session:null]);if($reconnectReserve->rowCount()===0)continue;
  $text="🟢 <b>PPPoE CONNECT KEMBALI</b>\n\nRouter : <b>".htmlspecialchars($routerName,ENT_QUOTES,'UTF-8')."</b>\nUsername : <b>".htmlspecialchars($username,ENT_QUOTES,'UTF-8')."</b>\nIP : ".htmlspecialchars($address,ENT_QUOTES,'UTF-8')."\nProfile : ".htmlspecialchars($profile,ENT_QUOTES,'UTF-8')."\nCaller-ID : ".htmlspecialchars($caller,ENT_QUOTES,'UTF-8')."\nWaktu : ".date('d-m-Y H:i:s');[$ok,$err]=$sendTelegram($text);if($ok)$reconnectSent++;else{$reconnectRemove->execute([$reconnectKey]);if($err!=='not_configured')$errors[]=$username.' reconnect: '.$err;}
 }
 echo json_encode(['success'=>true,'sent'=>$sent,'skipped'=>$skipped,'logged'=>$logged,'health_alerts'=>$healthAlerts,'reconnect_sent'=>$reconnectSent,'errors'=>$errors],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
}catch(Throwable $e){http_response_code(400);echo json_encode(['success'=>false,'message'=>$e->getMessage()],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}
