<?php
require_once __DIR__ . '/../Config/database.php';
ini_set('display_errors','0');header('Content-Type: application/json; charset=utf-8');
function out($ok,$data=[],$msg=''){echo json_encode(array_merge(['success'=>$ok,'message'=>$msg],$data),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
try{
$db=(new Database())->connect();
$username=trim((string)($_GET['username']??''));$routerId=(int)($_GET['router_id']??0);$range=strtolower((string)($_GET['range']??'24h'));$allowed=['1h'=>1,'6h'=>6,'24h'=>24,'7d'=>168,'30d'=>720];if(!isset($allowed[$range]))$range='24h';if($username==='')out(false,[],'Username wajib diisi.');$hours=$allowed[$range];
$hasRouter=$db->query("SHOW COLUMNS FROM pppoe_traffic_history LIKE 'router_id'")->fetch(PDO::FETCH_ASSOC);if(!$hasRouter){$db->exec("ALTER TABLE pppoe_traffic_history ADD router_id INT NULL AFTER id");$db->exec("ALTER TABLE pppoe_traffic_history ADD KEY idx_router_user_time(router_id,username,recorded_at)");}
$where='username=? AND recorded_at>=DATE_SUB(NOW(),INTERVAL '.$hours.' HOUR)';$params=[$username];if($routerId>0){$where='router_id=? AND '.$where;array_unshift($params,$routerId);}
$q=$db->prepare("SELECT username,ip_address,interface_name,profile,bytes_in,bytes_out,packets_in,packets_out,recorded_at,router_id FROM pppoe_traffic_history WHERE {$where} ORDER BY recorded_at ASC LIMIT 2000");$q->execute($params);$rows=$q->fetchAll();
$labels=[];$downloadSpeed=[];$uploadSpeed=[];$details=[];$lastRx=0;$lastTx=0;$firstAt=null;$lastAt=null;$peakDownload=0;$peakUpload=0;$sumDownload=0;$sumUpload=0;$speedCount=0;$prev=null;$totalDownload=0;$totalUpload=0;
foreach($rows as $r){$ts=strtotime($r['recorded_at']);$rx=(int)$r['bytes_in'];$tx=(int)$r['bytes_out'];$labels[]=date('H:i:s',$ts);$download=0;$upload=0;if($prev){$dt=max(1,$ts-$prev['ts']);$upload=max(0,$rx-$prev['rx'])*8/$dt;$download=max(0,$tx-$prev['tx'])*8/$dt;if($dt<=120){$peakDownload=max($peakDownload,$download);$peakUpload=max($peakUpload,$upload);$sumDownload+=$download;$sumUpload+=$upload;$speedCount++;$totalDownload+=max(0,$tx-$prev['tx']);$totalUpload+=max(0,$rx-$prev['rx']);}}$downloadSpeed[]=round($download,2);$uploadSpeed[]=round($upload,2);$details[]=['time'=>date('Y-m-d H:i:s',$ts),'rx'=>$rx,'tx'=>$tx,'download_bps'=>round($download,2),'upload_bps'=>round($upload,2)];$prev=['ts'=>$ts,'rx'=>$rx,'tx'=>$tx];$lastRx=$rx;$lastTx=$tx;$firstAt??=$r['recorded_at'];$lastAt=$r['recorded_at'];}
$meta=[];if($rows){$last=end($rows);$meta=['username'=>$username,'ip_address'=>$last['ip_address'],'interface'=>$last['interface_name'],'profile'=>$last['profile'],'router_id'=>$last['router_id']];}$avgDownload=$speedCount?$sumDownload/$speedCount:0;$avgUpload=$speedCount?$sumUpload/$speedCount:0;$duration=($firstAt&&$lastAt)?max(0,strtotime($lastAt)-strtotime($firstAt)):0;
out(true,['range'=>$range,'hours'=>$hours,'router_id'=>$routerId,'records'=>count($rows),'labels'=>$labels,'download_speed'=>$downloadSpeed,'upload_speed'=>$uploadSpeed,'details'=>$details,'meta'=>$meta,'first_at'=>$firstAt,'last_at'=>$lastAt,'duration_seconds'=>$duration,'latest_rx'=>$lastRx,'latest_tx'=>$lastTx,'download_bytes'=>$totalDownload,'upload_bytes'=>$totalUpload,'average_download_bps'=>round($avgDownload,2),'average_upload_bps'=>round($avgUpload,2),'peak_download_bps'=>round($peakDownload,2),'peak_upload_bps'=>round($peakUpload,2),'valid_speed_samples'=>$speedCount]);
}catch(Throwable $e){http_response_code(500);out(false,[],$e->getMessage());}
