<?php
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
require_once __DIR__.'/../Config/database.php';
try{$pdo=(new Database())->connect();$pdo->exec("CREATE TABLE IF NOT EXISTS pppoe_disconnect_history (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,router_id INT NOT NULL,router_name VARCHAR(128),username VARCHAR(128) NOT NULL,address VARCHAR(64),profile VARCHAR(128),caller_id VARCHAR(128),uptime VARCHAR(64),disconnected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_router_time(router_id,disconnected_at),KEY idx_user_time(username,disconnected_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$rid=(int)($_GET['router_id']??0);$where=$rid>0?' WHERE router_id=:rid':'';$p=$rid>0?[':rid'=>$rid]:[];
$today=$pdo->prepare("SELECT COUNT(*) FROM pppoe_disconnect_history WHERE disconnected_at>=CURDATE()".($rid>0?' AND router_id=:rid':''));$today->execute($p);$today=(int)$today->fetchColumn();
$week=$pdo->prepare("SELECT COUNT(*) FROM pppoe_disconnect_history WHERE disconnected_at>=DATE_SUB(NOW(),INTERVAL 7 DAY)".($rid>0?' AND router_id=:rid':''));$week->execute($p);$week=(int)$week->fetchColumn();
$month=$pdo->prepare("SELECT COUNT(*) FROM pppoe_disconnect_history WHERE disconnected_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)".($rid>0?' AND router_id=:rid':''));$month->execute($p);$month=(int)$month->fetchColumn();
$u=$pdo->prepare("SELECT username,COUNT(*) total FROM pppoe_disconnect_history".$where." GROUP BY username ORDER BY total DESC,username LIMIT 10");$u->execute($p);$users=$u->fetchAll(PDO::FETCH_ASSOC);
$r=$pdo->prepare("SELECT router_name,router_id,COUNT(*) total FROM pppoe_disconnect_history".$where." GROUP BY router_id,router_name ORDER BY total DESC LIMIT 10");$r->execute($p);$routers=$r->fetchAll(PDO::FETCH_ASSOC);
$h=$pdo->prepare("SELECT DATE_FORMAT(disconnected_at,'%H:00') hour,COUNT(*) total FROM pppoe_disconnect_history WHERE disconnected_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)".($rid>0?' AND router_id=:rid':'')." GROUP BY HOUR(disconnected_at) ORDER BY HOUR(disconnected_at)");$h->execute($p);$hours=$h->fetchAll(PDO::FETCH_ASSOC);
echo json_encode(['success'=>true,'summary'=>['today'=>$today,'week'=>$week,'month'=>$month],'top_users'=>$users,'top_routers'=>$routers,'hours'=>$hours],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
}catch(Throwable $e){http_response_code(400);echo json_encode(['success'=>false,'message'=>$e->getMessage()],JSON_UNESCAPED_UNICODE);}
