<?php
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__.'/../Config/database.php';
require_once __DIR__.'/../Config/mikrotik.php';
try{
  $range=$_GET['range']??'24h';$allowed=['1h'=>'1 HOUR','6h'=>'6 HOUR','24h'=>'24 HOUR','7d'=>'7 DAY','30d'=>'30 DAY'];if(!isset($allowed[$range]))$range='24h';
  $pdo=(new Database())->connect();
  $config=new MikroTikConfig();$routerId=(int)($_GET['router_id']??0);$router=null;if($routerId>0)$router=$config->getRouterById($routerId);else $router=$config->getRouter();
  if(!$router)throw new RuntimeException('Router tidak ditemukan');$routerId=(int)$router['id'];
  $pdo->exec("CREATE TABLE IF NOT EXISTS pppoe_traffic_history (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, router_id INT NULL, username VARCHAR(128) NOT NULL, session_id VARCHAR(128) NULL, ip_address VARCHAR(64) NULL, interface_name VARCHAR(128) NULL, profile VARCHAR(128) NULL, bytes_in BIGINT UNSIGNED NOT NULL DEFAULT 0, bytes_out BIGINT UNSIGNED NOT NULL DEFAULT 0, packets_in BIGINT UNSIGNED NOT NULL DEFAULT 0, packets_out BIGINT UNSIGNED NOT NULL DEFAULT 0, recorded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), KEY idx_router_user_time(router_id,username,recorded_at), KEY idx_session_time(session_id,recorded_at), KEY idx_time(recorded_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  $cols=$pdo->query("SHOW COLUMNS FROM pppoe_traffic_history LIKE 'router_id'")->fetch();if(!$cols)$pdo->exec("ALTER TABLE pppoe_traffic_history ADD COLUMN router_id INT NULL AFTER id");
  $sql="SELECT id,username,session_id,profile,bytes_in,bytes_out,recorded_at FROM pppoe_traffic_history WHERE router_id=? AND recorded_at>=DATE_SUB(NOW(), INTERVAL {$allowed[$range]}) ORDER BY username ASC, COALESCE(session_id,'') ASC, recorded_at ASC, id ASC";$stmt=$pdo->prepare($sql);$stmt->execute([$routerId]);
  $users=[];$prev=[];
  foreach($stmt as $r){$username=(string)$r['username'];$session=(string)($r['session_id']??'');$key=$username.'|'.$session;if(!isset($users[$username]))$users[$username]=['username'=>$username,'profile'=>(string)($r['profile']??''),'download_bytes'=>0.0,'upload_bytes'=>0.0,'records'=>0,'first_at'=>$r['recorded_at'],'last_at'=>$r['recorded_at']];$u=&$users[$username];$u['records']++;if($r['recorded_at']<$u['first_at'])$u['first_at']=$r['recorded_at'];if($r['recorded_at']>$u['last_at'])$u['last_at']=$r['recorded_at'];if((string)($r['profile']??'')!=='')$u['profile']=(string)$r['profile'];$in=(float)$r['bytes_in'];$out=(float)$r['bytes_out'];if(isset($prev[$key])){$di=$in-$prev[$key]['in'];$do=$out-$prev[$key]['out'];if($di>0)$u['upload_bytes']+=$di;if($do>0)$u['download_bytes']+=$do;}$prev[$key]=['in'=>$in,'out'=>$out];unset($u);}
  $rows=[];foreach($users as $u){$u['total_bytes']=$u['download_bytes']+$u['upload_bytes'];$rows[]=$u;}usort($rows,function($a,$b){return $b['total_bytes']<=>$a['total_bytes'];});echo json_encode(['success'=>true,'range'=>$range,'router_id'=>$routerId,'router_name'=>$router['router_name']??'','users'=>$rows,'timestamp'=>date('c')],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
}catch(Throwable $e){http_response_code(500);echo json_encode(['success'=>false,'message'=>$e->getMessage()]);}
