<?php
require_once __DIR__ . '/../config/mikrotik.php';
require_once __DIR__ . '/../library/routeros_api.class.php';
ini_set('display_errors','0'); header('Content-Type: application/json; charset=utf-8');
function pppoe_json($ok,$msg='',$data=[],$code=200){http_response_code($code);echo json_encode(array_merge(['success'=>$ok,'message'=>$msg],$data),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function numv($v){return is_numeric($v)?(float)$v:0.0;}
function firstv($r,$keys,$default=0){foreach($keys as $k){if(isset($r[$k])&&$r[$k]!==''&&$r[$k]!==null)return $r[$k];}return $default;}
function active_print($api){$props='.id,name,address,caller-id,uptime,service,bytes-in,bytes-out,packets-in,packets-out,session-id';$rows=(array)$api->comm('/ppp/active/print',['.proplist'=>$props,'stats'=>'']);$has=false;foreach($rows as $r){if(is_array($r)&&((isset($r['bytes-in'])&&is_numeric($r['bytes-in']))||(isset($r['bytes-out'])&&is_numeric($r['bytes-out'])))){$has=true;break;}}return $has?$rows:(array)$api->comm('/ppp/active/print',['stats'=>'']);}
try{
$config=new MikroTikConfig();$router=$config->getRouter();if(!$router)throw new Exception('Konfigurasi MikroTik tidak ditemukan.');$api=new RouterosAPI();$api->debug=false;if(!$api->connect($router['ip_address'],$router['username'],$router['password'],$router['api_port']))throw new Exception('Gagal terhubung ke MikroTik.');
$activeRows=active_print($api);$secretRows=(array)$api->comm('/ppp/secret/print');$profileRows=(array)$api->comm('/ppp/profile/print');
$secretMap=[];foreach($secretRows as $r){if(is_array($r))$secretMap[(string)($r['name']??'')]=['profile'=>$r['profile']??'default','service'=>$r['service']??'pppoe'];}
$interfaces=(array)$api->comm('/interface/print');$ifMap=[];foreach($interfaces as $r){if(!is_array($r))continue;$iname=(string)($r['name']??'');if($iname==='')continue;$clean=strtolower(trim($iname,'<>'));$ifMap[$clean]=$r;}
$active=[];$totalRx=0;$totalTx=0;
foreach($activeRows as $r){if(!is_array($r))continue;$name=(string)($r['name']??'-');$rx=numv(firstv($r,['bytes-in','rx-byte','rx_bytes']));$tx=numv(firstv($r,['bytes-out','tx-byte','tx_bytes']));$candidate=['pppoe-'.strtolower($name),strtolower($name)];foreach($candidate as $c){if(isset($ifMap[$c])){$ir=$ifMap[$c];$rx=max($rx,numv(firstv($ir,['rx-byte','rx_bytes','bytes-in'])));$tx=max($tx,numv(firstv($ir,['tx-byte','tx_bytes','bytes-out'])));break;}}$totalRx+=$rx;$totalTx+=$tx;$active[]=['id'=>$r['.id']??'','name'=>$name,'address'=>$r['address']??'-','caller_id'=>$r['caller-id']??'-','uptime'=>$r['uptime']??'-','service'=>$r['service']??($secretMap[$name]['service']??'pppoe'),'profile'=>$secretMap[$name]['profile']??'default','bytes_in'=>$rx,'bytes_out'=>$tx,'total_bytes'=>$rx+$tx,'packets_in'=>numv(firstv($r,['packets-in','rx-packet'])),'packets_out'=>numv(firstv($r,['packets-out','tx-packet'])),'session_id'=>$r['session-id']??'-'];}
$enabled=$disabled=0;$services=[];$profileUsage=[];foreach($secretRows as $r){if(!is_array($r))continue;$d=(($r['disabled']??'false')==='true');if($d)$disabled++;else $enabled++;$s=$r['service']??'pppoe';$services[$s]=($services[$s]??0)+1;$p=$r['profile']??'default';$profileUsage[$p]=($profileUsage[$p]??0)+1;}
usort($active,fn($a,$b)=>$b['total_bytes']<=>$a['total_bytes']);$api->disconnect();pppoe_json(true,'',['active_count'=>count($active),'account_count'=>count($secretRows),'profile_count'=>count($profileRows),'enabled_accounts'=>$enabled,'disabled_accounts'=>$disabled,'total_rx_bytes'=>$totalRx,'total_tx_bytes'=>$totalTx,'total_traffic_bytes'=>$totalRx+$totalTx,'active'=>$active,'top_users'=>array_slice($active,0,5),'services'=>$services,'profile_usage'=>$profileUsage,'updated_at'=>date('Y-m-d H:i:s')]);
}catch(Throwable $e){pppoe_json(false,$e->getMessage(),[],500);}
